#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Aug 08 18:22:24 KST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=BSL_v10.1.3.zip
enableShaders=true
